# Generated by Django 3.2.4 on 2021-06-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_user_thread_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='message',
            new_name='messages',
        ),
    ]
